### ISSUE TITLE
Vanilla Javascript Version

### ISSUE THREAD

**Issue by dvlwj** [fasih-uxd/Fasih-Carousel#1]
Need Vanilla Javascript version for this.

**Comment by devcer** [comment]
Let me know how I can help with this.

**Comment by Snelius30** [comment]
I guess i can implement this one.

**Comment by Snelius30** [comment]
@devcer U can just do it :) Rework this script with native JS without any JQ code.

**Comment by dvlwj** [comment]
@devcer 
> Let me know how I can help with this.
@Snelius30 
>@devcer U can just do it :) Rework this script with native JS without any JQ code.

yes, devcer, just like what Snelius30 you can rewrite this script with native JS without any JQ code. Sorry, late reply. 🙂

**Comment by Snelius30** [comment]
Well, I can do that if @devcer not. I see useful task here.

**Comment by dvlwj** [comment]
@Snelius30  sure, its not a problem for me if it you or @devcer  😄 .

Just remember to pull request it as a new file instead of replace the JQuery one.

**Comment by dvlwj** [comment]
Hi @Snelius30  i think you can do it, since we doesn't have any news from @devcer

**Comment by Snelius30** [comment]
OK, i will handle it.
